/**
 * Purchase Validator
 *
 * Provides idempotent receipt processing for developer products.
 *
 * Roblox guarantees that a `ProcessReceipt` callback can be called more than
 * once for the same `PurchaseId` if the previous attempt returned
 * `"NotProcessedYet"`.  This validator uses an in-memory Set to prevent
 * duplicate grants within the same server session.  If the server restarts the
 * Set is lost, but Roblox will retry the callback and the handler is expected
 * to be idempotent for cross-restart cases (e.g., check before granting).
 *
 * Security note: the `PurchaseId` is generated by Roblox and is globally
 * unique.  It is safe to use as an idempotency key.
 */

import { setSize } from "@rbx/core";
import { ProductReceipt, PurchaseDecision } from "./types";
import { DeveloperProductRegistry } from "./developer-products";

export class PurchaseValidator {
  /**
   * In-memory set of `PurchaseId` values that have been successfully granted
   * in this server session.  Prevents double-granting if Roblox re-fires the
   * ProcessReceipt callback before it receives the `PurchaseGranted` response.
   */
  private grantedPurchases = new Set<string>();

  constructor(private readonly registry: DeveloperProductRegistry) {}

  // --------------------------------------------------------------------------
  // Core processing
  // --------------------------------------------------------------------------

  /**
   * Validate and process a purchase receipt with idempotency protection.
   *
   * 1. If this `PurchaseId` has already been granted in this session, return
   *    `"PurchaseGranted"` immediately (idempotency).
   * 2. Delegate to the registered product handler.
   * 3. If the handler returns `"PurchaseGranted"`, record the PurchaseId so
   *    future retries are short-circuited.
   */
  process(receipt: ProductReceipt): PurchaseDecision {
    if (this.grantedPurchases.has(receipt.PurchaseId)) {
      return "PurchaseGranted";
    }

    const decision = this.registry.handleReceipt(receipt);

    if (decision === "PurchaseGranted") {
      this.grantedPurchases.add(receipt.PurchaseId);
    }

    return decision;
  }

  // --------------------------------------------------------------------------
  // Introspection (tests / admin)
  // --------------------------------------------------------------------------

  /**
   * Check if a `PurchaseId` has already been granted in this session.
   */
  isGranted(purchaseId: string): boolean {
    return this.grantedPurchases.has(purchaseId);
  }

  /**
   * Number of purchases granted in this server session.
   */
  grantedCount(): number {
    return setSize(this.grantedPurchases);
  }

  /**
   * Clear the granted set (for testing only).
   */
  resetForTesting(): void {
    this.grantedPurchases.clear();
  }
}
